### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by duaraghav8** [duaraghav8/sol-explore#1]
- [ ] write tests
- [ ] add visitor keys
- [ ] add syntax
- [x] add browser support
- [ ] Add commandline utility
- [ ] Demo on gh-pages
- [x] provide parent as 2nd argument for enter function

**Comment by yxliang01** [comment]
I can see there is a syntax file there. https://github.com/duaraghav8/sol-explore/blob/master/lib/syntax.js Is "add syntax" referring to what this file implements? By the way, I think it is kinda weird to see the object with all `key` `value` pairs having `key === value`. What does it really do? @duaraghav8

**Comment by duaraghav8** [comment]
I don't think it is being used anywhere. Been 2 years since I made a commit to this module, so can't be sure.
I think I wrote it with the intention that I didn't want to hard-code reserved solidity words inside the main code. @yxliang01

**Comment by yxliang01** [comment]
I see. Thanks for clarifications! @duaraghav8
